#pragma once

#define ERROR_DETOURSNET_CLR 0xA0000000

#define ERROR_BAD_MODULE_PATH ERROR_DETOURSNET_CLR | 0x1
#define ERROR_CANNOT_CREATE_CLR_INSTANCE ERROR_DETOURSNET_CLR | 0x2
#define ERROR_CANNOT_GET_RUNTIME_V4 ERROR_DETOURSNET_CLR | 0x3
#define ERROR_CLR_NOT_LOADABLE ERROR_DETOURSNET_CLR | 0x4
#define ERROR_FAILED_TO_LOAD_INTERFACE ERROR_DETOURSNET_CLR | 0x5
#define ERROR_FAILED_TO_START_CLR ERROR_DETOURSNET_CLR | 0x6
#define ERROR_FAILED_TO_LOAD_DETOURSNET_ASSEMBLY ERROR_DETOURSNET_CLR | 0x7
